name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Chrome Update
       run: |
         wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
         echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
         sudo apt-get update
         sudo apt-get install google-chrome-stable
         google-chrome --version

      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: install deps
        run: npm ci

      - name: run lint
        run: npm run lint

      - name: run unit tests
        run: npm run test:ci

      - name: run tests
        run: npm run e2e:quick

      - name: run build test
        run: npm run build:demo

      - name: run build prod
        run: npm run build:lib
